### ISSUE TITLE
Update config.example.yml

### ISSUE THREAD

**Issue by coignard** [coignard/weblog#13]

**Comment by coignard** [comment]
```yaml
# Configuration Template for Weblog
# Fill in your values and rename this file to config.yml

# Author's full name
author_name: "Your Full Name"

# Description about the author or the blog
about_text: "I like trains."

# Full domain URL without trailing slash
domain: "https://example.com"

# Line width for text formatting
line_width: 72

# Prefix length for paragraph formatting
prefix_length: 3

# Directory where blog files are stored
weblog_dir: "/path/to/your/weblog/directory"

# Author email for footer copyright
author_email: "example@example.com"
```
